#配置spring

spring:
  jackson:
    time-zone: GMT+8
  mvc:
    format:
      date: yyyy-MM-dd
  thymeleaf:
    prefix: classpath:/template/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html



    #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/fcsystem?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    #security配置
  security:
      user:
        name: xc
        password: 123456
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
      # 静态资源配置
  #        ,file:${web.upload.path}
  #端口号配置
  main:
    allow-circular-references: true



server:
  port: 9091

web:
  upload:
    path: F:/JUZUN/ideaWS/crms/target/classes/upload/supplier/


#配置mybatis
mybatis:
  type-aliases-package: com.xc.fcsystem.dao.user
  mapper-locations: classpath:com/xc/fcsystem/dao/mapper/**.xml

