#配置spring

spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
  jackson:
    time-zone: GMT+8
  mvc:
    format:
      date: yyyy-MM-dd
  thymeleaf:
    prefix: classpath:/template/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html
    #encoding: UTF-8
    #content-type: text/html

    #数据库配置
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fcsystem?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
    #security配置
    security:
      user:
        name: xc
        password: 123456
  web:
    resources:
      static-locations: classpath:/static,classpath:/public,classpath:/resources/template,classpath:/META-INF/resources
      # 静态资源配置
#        ,file:${web.upload.path}
  #端口号配置

server:
  port: 9091

web:
  upload:
      path: F:/JUZUN/ideaWS/crms/target/classes/upload/supplier/




